export const ADD_TODO = 'add_todo'
export const DELETE_TODO = 'delete_todo'
export const TOGGLE_ALL = 'toggle_all'
export const TOGGLE = 'toggle'
export const UPDATE_TODO = 'update_todo'
export const UPDATE_FILTER = 'update_filter'
export const CLEAR = 'clear'
